= LeoDatabaseLearner - System Specification
19SM, 22TI, 15PV
1.1.0, 2020-10-23: Some notes
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

// print the toc here (not at the default position)
//toc::[]

== Pflichtenheft "Was mache ich"


=== Initial situation

The HTL Leonding is an HTL in Upper Austria. Central room with around 1400 students and the specialist departments
Media technology, IT, electronics and medical technology.In the scope of the IT departments
and media technology, the subject of databases (DBI / INSY) is taught.
An essential part of this course is the practical training in the database query language SQL.


=== Present situation

At the HTL Leonding an Oracle database is available to the students in order to be able to work with a database.
The teacher provides exercises for the students to perform.
There are already various exercise tools that can be found on the Internet.
However, these are mostly static and you can only learn the existing exercises.
In addition, the overview of the level of knowledge is not very clear. Also, you often have to pay for these tools to
use them.

=== Problem

In addition to the tasks provided by the teachers, it is advantageous for the students to be able to prepare for the
exams with additional tasks.
The teachers often provide additional examples, but sometimes without solutions.

=== Task
Creation of a software product for students and teachers at the HTL Leonding.
The system consists of 4 functions:

* Practice mode
* Learning mode (according to the learning card system, the incorrect examples are repeated from a set of tasks)
* Exam mode - student (simulated exam)
* Exam mode - teacher (assessed performance assessment)

The exam tasks can be created by teachers using the system.
The tasks are then evaluated.

The GUI is basically divided into 3 areas:

* Text / information (graphic representation of the data model)
* SQL statement to be entered by the student
* Feedback

The learning progress should be documented graphically.

==== Functional requirements

[plantuml]
----
@startuml
left to right direction
actor Student as s
actor Teacher as t

package LeoDatabaseLearner {
  usecase "practice SQL" as UC1
  usecase "take simulated exam" as UC2
  usecase "view knowledge level" as UC3
  usecase "execute exam" as UC4
  usecase "take exam" as UC5
  usecase "upload exercises/tests" as UC6
  usecase "view knowledge of students" as UC7
}
s --> UC1
s --> UC2
s --> UC3
s --> UC5

t --> UC4
t --> UC6
t --> UC7
@enduml
----
- practice SQL
- take simulated exam
- take exam
- view knowledge level

- upload exercises/tests
- execute exam
- view knowledge of students





==== Nichtfunktionale Anforderungen (NFA)
=== Ziele
=== Mengengerüst
=== Rahmenbedingungen
zB Vorgaben vom Auftraggeber

== Entwurf "Wie mache ich es"
=== Systemarchitektur
=== ...

== Projekthandbuch "Organisatorische Rahmenbedingungen"

=== GANTT-Diagramm

mit User-Stories (definiert in YouTrack)

[plantuml,gantt-protoype,png]
----
@startuml
[Test prototype] lasts 10 days
[Prototype completed] happens at [Test prototype]'s end
[Setup assembly line] lasts 12 days
[Setup assembly line] starts at [Test prototype]'s end
[Test prototype 2] lasts 3 days
[Test prototype 2] starts at [Prototype completed]'s end
@enduml
----
